---
# FIXME
- name: Install apt transport package
  apt: pkg={{ item }} state=latest
  with_items:
    - apt-transport-https

- name: Add Docker repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ apt_key_sig }}"
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: yes
    state: present

- name: Install Docker package
  apt:
    name: "{{ docker_pkg_name }}"
    state: latest
    update_cache: yes # FIXME
    cache_valid_time: 600 # FIXME

- name: Start Docker
  service: name=docker.io state=started enabled=yes
